### ISSUE TITLE
Decouple the service from DocumentDb, allow any storage

### ISSUE THREAD

**Issue by dluc** [Azure/telemetry-agent-java#20]
# Type of issue
- [ ] Bug
- [ ] New feature
- [x] Improvement

# Description
As a developer I want to be able to customize the microservice to storage telemetry and alerts in a storage of mine, for example Cassandra or Azure Tables. The code should allow to easily extend/plug in a new storage type without major refactoring.

**Comment by ppathan** [comment]
Closing this as we are going to work on it as part of reference architecture document
